name: Publish Docker Container

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  docker:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Spring Boot application
        run: mvn clean package -DskipTests

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
          -t ghcr.io/${{ github.repository_owner }}/enterprise-iot-kafka-gateway:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/enterprise-iot-kafka-gateway:latest
